version: '2'

services:
        web:
                build:
                        context: .
                        dockerfile: ./container/Dockerfile-web
                container_name: web_blog
                volumes:
                        - ./:/var/www/html
                ports:
                        - "80:80"
                environment:
                        - XDEBUG_CONFIG=remote_host=${DOCKER_HOST_IP}

        

